# yq script file used to update the Jekyll config file of https://github.com/jeandeaual/lilypond-jekyll-template
# See https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update
- command: update
  path: title
  value: Test
- command: update
  path: description
  value: Test partition.
- command: update
  path: baseurl
  value: /testly
- command: update
  path: url
  value: https://jeandeaual.github.io
- command: update
  path: repository
  value: jeandeaual/testly
