name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build
        uses: docker://jeandeaual/lilypond:2.20.0
        with:
          args: lilypond -dno-point-and-click -dmidi-extension='"midi"' -dembed-source-code test.ly
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: artifact
          path: .
